# Generated by Django 5.2.6 on 2025-09-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addition',
            options={'verbose_name': 'Доп. опция', 'verbose_name_plural': 'Доп. опции'},
        ),
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='bouquetflower',
            options={'verbose_name': 'Состав букета (позиция)', 'verbose_name_plural': 'Состав букета'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterModelOptions(
            name='courier',
            options={'verbose_name': 'Курьер', 'verbose_name_plural': 'Курьеры'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='flower',
            options={'verbose_name': 'Цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='addition',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='price',
        ),
        migrations.AlterField(
            model_name='addition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название доп. опции'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='additions',
            field=models.ManyToManyField(blank=True, to='flowerapp.addition', verbose_name='Доп. опции'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='events',
            field=models.ManyToManyField(to='flowerapp.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(through='flowerapp.BouquetFlower', to='flowerapp.flower', verbose_name='Цветы'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='bouquets/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название букета'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена букета'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.flower', verbose_name='Цветок'),
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заявка принята'), ('completed', 'Оказана'), ('rejected', 'Отклонена')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя курьера'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to='flowers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название цветка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerapp.bouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.TextField(verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='flowerapp.courier', verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('assembled', 'Собран'), ('delivering', 'Передан в доставку'), ('delivered', 'Доставлен')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
