# Generated by Django 5.2.6 on 2025-09-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_alter_addition_options_alter_bouquet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='image',
        ),
    ]
