# Generated by Django 5.2.6 on 2025-09-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0003_remove_flower_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='size',
        ),
        migrations.AlterField(
            model_name='bouquetflower',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='шт'),
        ),
    ]
