# Generated by Django 5.2.6 on 2025-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0004_remove_bouquet_description_remove_bouquet_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'ordering': ['name'], 'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AddField(
            model_name='bouquet',
            name='image_card',
            field=models.ImageField(blank=True, upload_to='bouquets/card/', verbose_name='Изображение карточка товара'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='bouquets/catalog/', verbose_name='Изображение каталог'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Высота, см'),
        ),
    ]
