# Generated by Django 5.2.6 on 2025-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0006_bouquet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='default_qty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='шт'),
        ),
    ]
