# Generated by Django 5.2.6 on 2025-09-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0007_addition_default_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать в «Рекомендуем»'),
        ),
    ]
