# Generated by Django 5.2.6 on 2025-09-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0008_bouquet_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='potxSp8CNz2L70qm0Pom', max_length=20, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('1', 'Как можно скорее'), ('2', 'с 10:00 до 12:00'), ('3', 'с 12:00 до 14:00'), ('4', 'с 14:00 до 16:00'), ('5', 'с 16:00 до 18:00'), ('6', 'с 18:00 до 20:00')], default='asap', max_length=10, verbose_name='Время доставки'),
        ),
    ]
